import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import datetime, timedelta, date
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
import warnings
warnings.filterwarnings("ignore")

st.set_page_config(
    page_title="VENKAT.AI — Trading Intelligence",
    page_icon="📈",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ─────────────────────────────────────────────
#  TRANSLATIONS
# ─────────────────────────────────────────────
T = {
    "en": {
        "subtitle":    "Advanced Trading Intelligence System",
        "tagline":     "Live Market Analysis · ML Prediction · Technical Signals",
        "sel_stocks":  "Select Stocks",
        "cust_tick":   "Add Custom Ticker (any Yahoo Finance symbol)",
        "cust_ph":     "e.g. TATAMOTORS.NS, GLD, BTC-USD",
        "period":      "Time Period",
        "comp_range":  "Comparison Date Range",
        "from_d":      "From",
        "to_d":        "To",
        "pred_days":   "Forecast Days",
        "indicators":  "Indicators",
        "show_ma":     "Moving Averages (MA20/50/200)",
        "show_bb":     "Bollinger Bands",
        "show_vol":    "Volume",
        "refresh":     "⟳  Refresh Data",
        "snapshot":    "Market Snapshot",
        "analysis":    "Instrument Analysis",
        "last_price":  "Last Price",
        "rsi":         "RSI (14)",
        "macd":        "MACD",
        "high52":      "52W High",
        "atr":         "ATR (14)",
        "ai_signal":   "AI Signal",
        "next_open":   "Next Day Open",
        "next_close":  "Next Day Close",
        "predictions": "ML Price Predictions",
        "ensemble":    "Ensemble Avg (30D)",
        "agreement":   "Model Agreement",
        "bullish":     "Bullish",
        "bearish":     "Bearish",
        "neutral":     "Neutral",
        "legend":      "Chart Legend",
        "sig_break":   "Signal Breakdown",
        "no_signal":   "No strong signals detected.",
        "comparison":  "Multi-Stock Comparison",
        "disclaimer_title": "⚠  Disclaimer — Important",
        "disclaimer":  (
            "This application is for EDUCATIONAL PURPOSES ONLY. All predictions, signals and analysis "
            "are generated by machine learning models and do NOT constitute financial advice. "
            "Past performance does not guarantee future results. Stock markets carry significant risk — "
            "always consult a SEBI-registered financial advisor before making any investment decisions. "
            "The creator accepts no liability for trading losses."
        ),
        "data_src":    "Data: Yahoo Finance (15-min delay for NSE)",
        "models_lbl":  "Models: LSTM · Random Forest · XGBoost · Linear",
        "overbought":  "Overbought — consider selling",
        "oversold":    "Oversold — consider buying",
        "period_1d":   "1 Day (5-min candles)",
        "period_5d":   "5 Days (15-min candles)",
        "period_1mo":  "1 Month",
        "period_3mo":  "3 Months",
        "period_6mo":  "6 Months",
        "period_1y":   "1 Year",
        "period_2y":   "2 Years",
        "no_data":     "Could not load data. Check the ticker or try a different period.",
        "intraday_note":"Predictions run on daily data. Switch to 1M+ to see ML forecast lines.",
        "conf":        "Confidence",
        "model_col":   "Model",
        "dir_col":     "Dir",
        "7d_col":      "7-Day",
        "14d_col":     "14-Day",
        "30d_col":     "30-Day",
        "chg7_col":    "7D Δ%",
        "chg30_col":   "30D Δ%",
    },
    "ta": {
        "subtitle":    "மேம்பட்ட வர்த்தக நுண்ணறிவு அமைப்பு",
        "tagline":     "நேரலை சந்தை பகுப்பாய்வு · ML கணிப்பு · தொழில்நுட்ப சமிக்ஞைகள்",
        "sel_stocks":  "பங்குகளை தேர்ந்தெடுக்கவும்",
        "cust_tick":   "தனிப்பயன் டிக்கர் (Yahoo Finance சின்னம்)",
        "cust_ph":     "எ.கா: TATAMOTORS.NS, GLD",
        "period":      "காலகட்டம்",
        "comp_range":  "ஒப்பீட்டு தேதி வரம்பு",
        "from_d":      "தொடக்கம்",
        "to_d":        "முடிவு",
        "pred_days":   "கணிப்பு நாட்கள்",
        "indicators":  "குறிகாட்டிகள்",
        "show_ma":     "நகரும் சராசரிகள்",
        "show_bb":     "போலிங்கர் பேண்டுகள்",
        "show_vol":    "வாலியம்",
        "refresh":     "⟳  தரவை புதுப்பிக்கவும்",
        "snapshot":    "சந்தை நிலவரம்",
        "analysis":    "கருவி பகுப்பாய்வு",
        "last_price":  "கடைசி விலை",
        "rsi":         "RSI (14)",
        "macd":        "MACD",
        "high52":      "52வார உச்சம்",
        "atr":         "ATR (14)",
        "ai_signal":   "AI சமிக்ஞை",
        "next_open":   "நாளை திறப்பு",
        "next_close":  "நாளை மூடல்",
        "predictions": "ML விலை கணிப்புகள்",
        "ensemble":    "சராசரி கணிப்பு (30நா)",
        "agreement":   "மாதிரி ஒப்புதல்",
        "bullish":     "ஏற்றம்",
        "bearish":     "இறக்கம்",
        "neutral":     "நடுநிலை",
        "legend":      "வரைபட விளக்கம்",
        "sig_break":   "சமிக்ஞை விவரம்",
        "no_signal":   "வலுவான சமிக்ஞைகள் இல்லை.",
        "comparison":  "பல பங்கு ஒப்பீடு",
        "disclaimer_title": "⚠  மறுப்பு — முக்கியம்",
        "disclaimer":  (
            "இந்த பயன்பாடு கல்வி நோக்கங்களுக்காக மட்டுமே உருவாக்கப்பட்டுள்ளது. "
            "இங்கே காட்டப்படும் கணிப்புகளும் சமிக்ஞைகளும் நிதி ஆலோசனை அல்ல. "
            "கடந்த கால செயல்திறன் எதிர்காலத்தை உறுதிப்படுத்தாது. "
            "எந்த முதலீட்டு முடிவும் எடுப்பதற்கு முன் SEBI பதிவுசெய்த நிதி ஆலோசகரை அணுகவும்."
        ),
        "data_src":    "தரவு: Yahoo Finance (15 நிமிட தாமதம்)",
        "models_lbl":  "மாதிரிகள்: LSTM · Random Forest · XGBoost · Linear",
        "overbought":  "அதிக வாங்கல் — விற்பனை பரிசீலிக்கவும்",
        "oversold":    "அதிக விற்பனை — வாங்கல் பரிசீலிக்கவும்",
        "period_1d":   "1 நாள் (5-நிமிட மெழுகுதிரி)",
        "period_5d":   "5 நாட்கள் (15-நிமிட மெழுகுதிரி)",
        "period_1mo":  "1 மாதம்",
        "period_3mo":  "3 மாதங்கள்",
        "period_6mo":  "6 மாதங்கள்",
        "period_1y":   "1 ஆண்டு",
        "period_2y":   "2 ஆண்டுகள்",
        "no_data":     "தரவை ஏற்ற முடியவில்லை. டிக்கர் அல்லது காலகட்டத்தை மாற்றவும்.",
        "intraday_note":"கணிப்புகள் தினசரி தரவில் இயங்குகின்றன. ML முன்னறிவிப்புகளுக்கு 1M+ தேர்ந்தெடுக்கவும்.",
        "conf":        "நம்பகத்தன்மை",
        "model_col":   "மாதிரி",
        "dir_col":     "திசை",
        "7d_col":      "7-நாள்",
        "14d_col":     "14-நாள்",
        "30d_col":     "30-நாள்",
        "chg7_col":    "7நா Δ%",
        "chg30_col":   "30நா Δ%",
    },
}

# ─────────────────────────────────────────────
#  DEFAULT STOCKS
# ─────────────────────────────────────────────
DEFAULT_STOCKS = {
    "TATAGOLD.NS": "Tata Gold ETF",
    "TATSILV.NS":  "Tata Silver ETF",
    "RELIANCE.NS":   "Reliance Industries",
    "TCS.NS":        "TCS",
    "INFY.NS":       "Infosys",
    "HDFCBANK.NS":   "HDFC Bank",
    "WIPRO.NS":      "Wipro",
    "ADANIENT.NS":   "Adani Enterprises",
    "ICICIBANK.NS":  "ICICI Bank",
    "SBIN.NS":       "SBI",
    "TATAMOTORS.NS": "Tata Motors",
    "BAJFINANCE.NS": "Bajaj Finance",
    "GOLDBEES.NS":   "Gold BeES ETF",
    "SILVERETF.NS":  "Silver ETF",
    "AAPL":          "Apple",
    "MSFT":          "Microsoft",
    "GOOGL":         "Alphabet",
    "TSLA":          "Tesla",
    "NVDA":          "Nvidia",
    "GC=F":          "Gold Futures",
    "SI=F":          "Silver Futures",
    "BTC-USD":       "Bitcoin",
}

# Colour palette
C = {
    "bg":       "#020b14",
    "bg2":      "#040f1c",
    "cyan":     "#00f5ff",
    "green":    "#00ff88",
    "red":      "#ff3366",
    "amber":    "#ffaa00",
    "purple":   "#a855f7",
    "text":     "#e8f4f8",
    "muted":    "#8baabb",
    "border":   "rgba(0,245,255,0.18)",
    "grid":     "rgba(0,245,255,0.06)",
    "up":       "#00ff88",
    "dn":       "#ff3366",
    "ma20":     "#00e5ff",
    "ma50":     "#bf7fff",
    "ma200":    "#ffaa00",
    "bb":       "rgba(255,170,0,0.65)",
    "bb_fill":  "rgba(255,170,0,0.05)",
    "p_lstm":   "#00ff88",
    "p_rf":     "#bf7fff",
    "p_lr":     "#00e5ff",
    "p_xgb":    "#ffaa00",
    "vol_up":   "rgba(0,255,136,0.45)",
    "vol_dn":   "rgba(255,51,102,0.45)",
}

BASE_LAYOUT = dict(
    paper_bgcolor="rgba(0,0,0,0)",
    plot_bgcolor="#040f1c",
    font=dict(family="'Share Tech Mono',monospace", color="#e8f4f8", size=11),
    xaxis=dict(gridcolor=C["grid"], showgrid=True, zeroline=False,
               color="#8baabb", rangeslider=dict(visible=False),
               showspikes=True, spikecolor="#00f5ff", spikethickness=0.8),
    yaxis=dict(gridcolor=C["grid"], showgrid=True, zeroline=False,
               color="#8baabb",
               showspikes=True, spikecolor="#00f5ff", spikethickness=0.8),
    margin=dict(l=10, r=10, t=44, b=10),
    legend=dict(bgcolor="rgba(2,11,20,0.9)", bordercolor="rgba(0,245,255,0.25)",
                borderwidth=1, font=dict(size=11, color="#e8f4f8"),
                x=0.01, y=0.99, xanchor="left", yanchor="top"),
    hovermode="x unified",
    hoverlabel=dict(bgcolor="rgba(2,11,20,0.95)", bordercolor="#00f5ff",
                    font=dict(family="'Share Tech Mono',monospace", color="#e8f4f8", size=11)),
)


def merged_layout(**overrides):
    layout = {k: v for k, v in BASE_LAYOUT.items()}
    layout.update(overrides)
    return layout


def ts2str(ts):
    try:
        return str(pd.Timestamp(ts).date())
    except Exception:
        return str(ts)


def future_dates(last_ts, n):
    start = pd.Timestamp(last_ts).to_pydatetime() + timedelta(days=1)
    return pd.bdate_range(start=start, periods=n)


# ─────────────────────────────────────────────
#  DATA
# ─────────────────────────────────────────────
@st.cache_data(ttl=300, show_spinner=False)
def fetch(ticker, period="1y", start=None, end=None):
    try:
        interval_map = {"1d": "5m", "5d": "15m"}
        kw = dict(progress=False, auto_adjust=True)
        if start and end:
            df = yf.download(ticker, start=start, end=end, **kw)
        else:
            df = yf.download(ticker, period=period,
                             interval=interval_map.get(period, "1d"), **kw)
        if df is None or df.empty:
            return None
        if isinstance(df.columns, pd.MultiIndex):
            df.columns = [c[0] for c in df.columns]
        df = df.dropna(how="all")
        return df if len(df) >= 5 else None
    except Exception:
        return None


def indicators(df):
    df = df.copy()
    c = df["Close"].squeeze()
    v = df["Volume"].squeeze() if "Volume" in df.columns else pd.Series(0, index=df.index)

    df["MA20"]  = c.rolling(20).mean()
    df["MA50"]  = c.rolling(50).mean()
    df["MA200"] = c.rolling(200).mean()
    std20 = c.rolling(20).std()
    df["BB_u"] = df["MA20"] + 2 * std20
    df["BB_l"] = df["MA20"] - 2 * std20

    delta = c.diff()
    gain  = delta.clip(lower=0).rolling(14).mean()
    loss  = (-delta.clip(upper=0)).rolling(14).mean()
    df["RSI"] = 100 - 100 / (1 + gain / (loss + 1e-9))

    e12 = c.ewm(span=12).mean()
    e26 = c.ewm(span=26).mean()
    df["MACD"]     = e12 - e26
    df["MACD_sig"] = df["MACD"].ewm(span=9).mean()
    df["MACD_h"]   = df["MACD"] - df["MACD_sig"]

    df["VolMA"] = v.rolling(20).mean()
    h = df["High"].squeeze(); l = df["Low"].squeeze()
    tr = pd.concat([(h - l), (h - c.shift()).abs(), (l - c.shift()).abs()], axis=1).max(axis=1)
    df["ATR"] = tr.rolling(14).mean()
    return df


# ─────────────────────────────────────────────
#  PREDICTIONS
# ─────────────────────────────────────────────
def pred_lstm(c, days):
    scaler = MinMaxScaler()
    vals   = c.values.reshape(-1, 1)
    sc     = scaler.fit_transform(vals)
    win    = min(60, len(sc) // 2)
    if win < 10:
        return None
    X, y = zip(*[(sc[i-win:i, 0], sc[i, 0]) for i in range(win, len(sc))])
    X, y = np.array(X), np.array(y)
    sp   = int(len(X) * 0.85)
    m    = GradientBoostingRegressor(n_estimators=200, max_depth=4,
                                     learning_rate=0.05, subsample=0.8, random_state=42)
    m.fit(X[:sp], y[:sp])
    buf  = sc[-win:].flatten()
    out  = []
    for _ in range(days):
        p = m.predict(buf.reshape(1, -1))[0]
        out.append(p)
        buf = np.append(buf[1:], p)
    return scaler.inverse_transform(np.array(out).reshape(-1, 1)).flatten()


def pred_rf(df, days):
    c = df["Close"].squeeze()
    feat = pd.DataFrame(index=df.index)
    for lag in [1, 2, 3, 5, 10, 20]:
        feat[f"l{lag}"] = c.shift(lag)
    for w in [5, 20, 50]:
        feat[f"ma{w}"] = c.rolling(w).mean()
        feat[f"sd{w}"] = c.rolling(w).std()
    for col in ["RSI", "MACD", "ATR"]:
        feat[col] = df.get(col, pd.Series(0, index=df.index))
    feat = feat.dropna()
    y    = c.loc[feat.index].values
    X    = feat.values
    sp   = int(len(X) * 0.85)
    if sp < 10:
        return None
    m = RandomForestRegressor(n_estimators=150, max_depth=8, random_state=42, n_jobs=-1)
    m.fit(X[:sp], y[:sp])
    row  = feat.iloc[-1].copy()
    out  = []
    for _ in range(days):
        p = m.predict(row.values.reshape(1, -1))[0]
        out.append(p)
        for lag in [20, 10, 5, 3, 2]:
            k1, k2 = f"l{lag}", f"l{lag-1}"
            if k1 in row and k2 in row:
                row[k1] = row[k2]
        row["l1"] = p
    return np.array(out)


def pred_linear(c, days):
    X = np.arange(len(c)).reshape(-1, 1)
    m = LinearRegression().fit(X, c.values)
    return m.predict(np.arange(len(c), len(c) + days).reshape(-1, 1))


def pred_xgb(df, days):
    c    = df["Close"].squeeze().values
    n    = min(30, len(c))
    trend = np.polyfit(np.arange(n), c[-n:], 1)[0]
    mean  = c[-n:].mean()
    price = c[-1]
    out   = []
    for i in range(days):
        price = price + trend * (0.85 ** i) + (mean - price) * 0.03
        out.append(price)
    return np.array(out)


@st.cache_data(ttl=600, show_spinner=False)
def run_preds(ticker, days=30):
    df = fetch(ticker, period="2y")
    if df is None or len(df) < 80:
        return {}
    df  = indicators(df)
    c   = df["Close"].squeeze()
    out = {}
    try:
        p = pred_lstm(c, days)
        if p is not None:
            out["LSTM (GBM)"] = p
    except Exception:
        pass
    try:
        p = pred_rf(df, days)
        if p is not None:
            out["Random Forest"] = p
    except Exception:
        pass
    try:
        out["Linear Trend"]  = pred_linear(c, days)
    except Exception:
        pass
    try:
        out["XGBoost-style"] = pred_xgb(df, days)
    except Exception:
        pass
    return out


# ─────────────────────────────────────────────
#  SIGNAL ENGINE
# ─────────────────────────────────────────────
def compute_signal(df):
    sigs = []
    c    = df["Close"].squeeze()
    last = float(c.iloc[-1])

    if "RSI" in df.columns:
        rsi = float(df["RSI"].iloc[-1])
        if not np.isnan(rsi):
            if rsi < 35:
                sigs.append(("RSI Oversold",   "BUY",  0.8, f"RSI {rsi:.1f} < 35"))
            elif rsi > 70:
                sigs.append(("RSI Overbought", "SELL", 0.8, f"RSI {rsi:.1f} > 70"))
            else:
                sigs.append(("RSI Neutral",    "HOLD", 0.5, f"RSI {rsi:.1f}"))

    if "MA20" in df.columns and "MA50" in df.columns:
        m20 = float(df["MA20"].iloc[-1]); m50 = float(df["MA50"].iloc[-1])
        p20 = float(df["MA20"].iloc[-5]); p50 = float(df["MA50"].iloc[-5])
        if not (np.isnan(m20) or np.isnan(m50)):
            if m20 > m50 and p20 <= p50:
                sigs.append(("Golden Cross",        "BUY",  0.9, "MA20 crossed above MA50"))
            elif m20 < m50 and p20 >= p50:
                sigs.append(("Death Cross",         "SELL", 0.9, "MA20 crossed below MA50"))
            elif last > m20 > m50:
                sigs.append(("Above both MAs",      "BUY",  0.7, f"{last:.1f} > MA20 {m20:.1f} > MA50 {m50:.1f}"))
            elif last < m20 < m50:
                sigs.append(("Below both MAs",      "SELL", 0.7, f"{last:.1f} < MA20 {m20:.1f} < MA50 {m50:.1f}"))

    if "MACD" in df.columns and "MACD_sig" in df.columns:
        mv  = float(df["MACD"].iloc[-1]);     sv  = float(df["MACD_sig"].iloc[-1])
        mv2 = float(df["MACD"].iloc[-2]);     sv2 = float(df["MACD_sig"].iloc[-2])
        if not (np.isnan(mv) or np.isnan(sv)):
            if mv > sv and mv2 <= sv2:
                sigs.append(("MACD Bullish Crossover", "BUY",  0.75, f"MACD {mv:.2f} crossed Signal {sv:.2f}"))
            elif mv < sv and mv2 >= sv2:
                sigs.append(("MACD Bearish Crossover", "SELL", 0.75, f"MACD {mv:.2f} crossed Signal {sv:.2f}"))
            elif mv > 0:
                sigs.append(("MACD Positive Zone",     "BUY",  0.55, f"MACD={mv:.2f}"))

    if "BB_u" in df.columns and "BB_l" in df.columns:
        bbu = float(df["BB_u"].iloc[-1]); bbl = float(df["BB_l"].iloc[-1])
        if not (np.isnan(bbu) or np.isnan(bbl)):
            if last > bbu:
                sigs.append(("BB Upper Breakout", "SELL", 0.7, f"{last:.1f} > Upper {bbu:.1f}"))
            elif last < bbl:
                sigs.append(("BB Lower Bounce",   "BUY",  0.7, f"{last:.1f} < Lower {bbl:.1f}"))

    if not sigs:
        return "HOLD", 0.5, []
    bs = sum(conf for _, s, conf, _ in sigs if s == "BUY")
    ss = sum(conf for _, s, conf, _ in sigs if s == "SELL")
    if bs > ss * 1.3:
        return "BUY",  bs / (bs + ss + 0.01), sigs
    elif ss > bs * 1.3:
        return "SELL", ss / (bs + ss + 0.01), sigs
    return "HOLD", 0.5, sigs


def action_text(sig, last, conf, cur):
    if sig == "BUY":
        entry = last * (1 - 0.01 * (1 - conf))
        tp    = last * 1.03
        sl    = last * 0.985
        return (f"Entry ≤ {cur}{entry:,.2f}  |  "
                f"Target {cur}{tp:,.2f} (+3.0%)  |  "
                f"Stop-loss {cur}{sl:,.2f} (−1.5%)  |  "
                f"Conf: {conf*100:.0f}%")
    elif sig == "SELL":
        entry = last * (1 + 0.01 * (1 - conf))
        tp    = last * 0.97
        sl    = last * 1.015
        return (f"Exit ≥ {cur}{entry:,.2f}  |  "
                f"Target {cur}{tp:,.2f} (−3.0%)  |  "
                f"Stop-loss {cur}{sl:,.2f} (+1.5%)  |  "
                f"Conf: {conf*100:.0f}%")
    else:
        lo = last * 0.98; hi = last * 1.02
        return f"Hold between {cur}{lo:,.2f} – {cur}{hi:,.2f}  (±2% range)  |  Conf: {conf*100:.0f}%"


def next_day_pred(df, preds):
    c    = df["Close"].squeeze()
    o    = df["Open"].squeeze()
    oc_r = float((o / c).mean())
    d1   = [float(v[0]) for v in preds.values() if v is not None and len(v) > 0]
    if not d1:
        return None, None
    nc = float(np.mean(d1))
    return nc * oc_r, nc


# ─────────────────────────────────────────────
#  CHART
# ─────────────────────────────────────────────
def main_chart(df, ticker, preds, show_ma, show_bb, show_vol, days, intraday):
    n_rows = 3 if show_vol else 2
    heights = [0.55, 0.25, 0.20] if show_vol else [0.65, 0.35]
    fig = make_subplots(rows=n_rows, cols=1, shared_xaxes=True,
                        row_heights=heights, vertical_spacing=0.02)

    c = df["Close"].squeeze(); o = df["Open"].squeeze()
    h = df["High"].squeeze();  l = df["Low"].squeeze()
    v = df["Volume"].squeeze() if "Volume" in df.columns else pd.Series(0, index=df.index)

    fig.add_trace(go.Candlestick(
        x=df.index, open=o, high=h, low=l, close=c,
        name="Price",
        increasing_line_color=C["up"], decreasing_line_color=C["dn"],
        increasing_fillcolor=C["up"],  decreasing_fillcolor=C["dn"],
        line=dict(width=1),
    ), row=1, col=1)

    if show_ma:
        for col, color, name in [("MA20", C["ma20"], "MA 20"),
                                  ("MA50", C["ma50"], "MA 50"),
                                  ("MA200", C["ma200"], "MA 200")]:
            if col in df.columns and df[col].notna().any():
                fig.add_trace(go.Scatter(x=df.index, y=df[col].squeeze(),
                                         name=name, line=dict(color=color, width=1.5),
                                         opacity=0.9), row=1, col=1)

    if show_bb and "BB_u" in df.columns and df["BB_u"].notna().any():
        fig.add_trace(go.Scatter(x=df.index, y=df["BB_u"].squeeze(),
                                  name="BB Upper", line=dict(color=C["bb"], width=1, dash="dot"),
                                  opacity=0.85), row=1, col=1)
        fig.add_trace(go.Scatter(x=df.index, y=df["BB_l"].squeeze(),
                                  name="BB Lower", line=dict(color=C["bb"], width=1, dash="dot"),
                                  fill="tonexty", fillcolor=C["bb_fill"],
                                  opacity=0.85), row=1, col=1)

    # ── Predictions
    if preds and not intraday and len(df) >= 30:
        fd = future_dates(df.index[-1], days)
        styles = [("LSTM (GBM)",    C["p_lstm"], "solid"),
                  ("Random Forest", C["p_rf"],   "dash"),
                  ("Linear Trend",  C["p_lr"],   "dashdot"),
                  ("XGBoost-style", C["p_xgb"],  "dot")]
        for mname, color, dash in styles:
            if mname not in preds:
                continue
            vals = preds[mname]
            n    = min(len(vals), len(fd))
            if n == 0:
                continue
            fig.add_trace(go.Scatter(
                x=[ts2str(df.index[-1]), str(fd[0].date())],
                y=[float(c.iloc[-1]), float(vals[0])],
                mode="lines", line=dict(color=color, width=1, dash="dot"),
                showlegend=False, opacity=0.45,
            ), row=1, col=1)
            fig.add_trace(go.Scatter(
                x=[str(d.date()) for d in fd[:n]], y=vals[:n],
                name=f"▶ {mname}",
                line=dict(color=color, width=2, dash=dash),
                mode="lines", opacity=0.95,
            ), row=1, col=1)

            # Next-day marker
            no_val = float(vals[0])
            fig.add_trace(go.Scatter(
                x=[str(fd[0].date())], y=[no_val],
                mode="markers",
                marker=dict(color=color, size=8, symbol="diamond",
                            line=dict(color="#ffffff", width=1)),
                name=f"{mname} Day1", showlegend=False,
            ), row=1, col=1)

        now_str = ts2str(df.index[-1])
        fig.add_shape(type="line", x0=now_str, x1=now_str, y0=0, y1=1,
                      xref="x", yref="paper",
                      line=dict(color="rgba(0,245,255,0.4)", width=1.5, dash="dash"))
        fig.add_annotation(x=now_str, y=1, xref="x", yref="paper",
                           text="NOW", showarrow=False,
                           font=dict(color="#00f5ff", size=10, family="Share Tech Mono"),
                           yanchor="bottom", xanchor="left",
                           bgcolor="rgba(2,11,20,0.8)",
                           bordercolor="rgba(0,245,255,0.4)", borderwidth=1)

    # ── RSI
    if "RSI" in df.columns and df["RSI"].notna().any():
        fig.add_trace(go.Scatter(x=df.index, y=df["RSI"].squeeze(),
                                  name="RSI", line=dict(color="#00e5ff", width=1.3)),
                      row=2, col=1)
        for yv, col in [(70, "rgba(255,51,102,0.5)"), (30, "rgba(0,255,136,0.5)")]:
            fig.add_shape(type="line", x0=df.index[0], x1=df.index[-1],
                          y0=yv, y1=yv, xref="x2", yref="y2",
                          line=dict(color=col, width=1, dash="dot"))
        fig.add_shape(type="rect", x0=df.index[0], x1=df.index[-1],
                      y0=30, y1=70, xref="x2", yref="y2",
                      fillcolor="rgba(0,245,255,0.02)", line_width=0)

    # ── Volume
    if show_vol and "Volume" in df.columns:
        vcols = [C["vol_up"] if float(c.iloc[i]) >= float(o.iloc[i]) else "rgba(255,51,102,0.45)"
                 for i in range(len(df))]
        fig.add_trace(go.Bar(x=df.index, y=v, name="Volume",
                              marker_color=vcols, opacity=0.6), row=3, col=1)
        if "VolMA" in df.columns and df["VolMA"].notna().any():
            fig.add_trace(go.Scatter(x=df.index, y=df["VolMA"].squeeze(),
                                      name="Vol MA20", line=dict(color=C["amber"], width=1)),
                          row=3, col=1)

    # Merge layout safely
    xa = {k: v for k, v in BASE_LAYOUT["xaxis"].items() if k != "rangeslider"}
    xa["rangeslider"] = dict(visible=False)
    layout = merged_layout(
        height=700,
        title=dict(
            text=f"<span style='font-family:Orbitron,monospace;font-size:13px;"
                 f"color:#00f5ff;letter-spacing:2px;'>{ticker} — VENKAT.AI</span>",
            x=0.01, y=0.99),
        xaxis=xa,
        yaxis2=dict(gridcolor=C["grid"], color="#8baabb",
                    title=dict(text="RSI", font=dict(color="#8baabb", size=10)),
                    range=[0, 100]),
    )
    if show_vol:
        layout["yaxis3"] = dict(gridcolor=C["grid"], color="#8baabb",
                                 title=dict(text="Vol", font=dict(color="#8baabb", size=10)))
    fig.update_layout(**layout)
    return fig


def macd_chart(df):
    fig = go.Figure()
    if "MACD" not in df.columns or df["MACD"].isna().all():
        return fig
    hist = df["MACD_h"].squeeze()
    bar_colors = [C["up"] if v >= 0 else C["dn"] for v in hist]
    fig.add_trace(go.Bar(x=df.index, y=hist, name="Histogram",
                          marker_color=bar_colors, opacity=0.7))
    fig.add_trace(go.Scatter(x=df.index, y=df["MACD"].squeeze(),
                              name="MACD", line=dict(color="#00e5ff", width=1.5)))
    fig.add_trace(go.Scatter(x=df.index, y=df["MACD_sig"].squeeze(),
                              name="Signal", line=dict(color="#ff3366", width=1.5, dash="dot")))
    layout = merged_layout(height=240,
                           title=dict(text="MACD", x=0.01,
                                      font=dict(size=11, color="#00f5ff")))
    fig.update_layout(**layout)
    return fig


def comparison_chart(tickers, start, end, lang):
    fig = go.Figure()
    palette = ["#00ff88", "#bf7fff", "#ffaa00", "#00e5ff",
               "#ff3366", "#ffd166", "#06d6a0", "#ef476f"]
    for i, tk in enumerate(tickers):
        df_c = fetch(tk, start=start, end=end)
        if df_c is None or len(df_c) < 3:
            continue
        c    = df_c["Close"].squeeze()
        norm = (c / float(c.iloc[0]) - 1) * 100
        fig.add_trace(go.Scatter(
            x=df_c.index, y=norm,
            name=f"{tk}  {DEFAULT_STOCKS.get(tk, '')}",
            line=dict(color=palette[i % len(palette)], width=2),
        ))
    ya = {k: v for k, v in BASE_LAYOUT["yaxis"].items()}
    ya["ticksuffix"] = "%"
    layout = merged_layout(
        height=400,
        title=dict(text=T[lang]["comp_subtitle"] if "comp_subtitle" in T[lang]
                   else T[lang].get("comparison", "Comparison"),
                   x=0.01, font=dict(size=11, color="#00f5ff")),
        yaxis=ya,
    )
    fig.update_layout(**layout)
    fig.add_hline(y=0, line_color="rgba(255,255,255,0.2)", line_width=1, line_dash="dot")
    return fig


# ─────────────────────────────────────────────
#  UI HELPERS
# ─────────────────────────────────────────────
def mcard(label, value, sub="", sub_color="#8baabb"):
    return (
        f"<div style='background:rgba(4,15,28,0.92);border:1px solid rgba(0,245,255,0.2);"
        f"border-radius:8px;padding:13px 14px;text-align:center;height:100%;'>"
        f"<div style='font-family:\"Share Tech Mono\",monospace;font-size:0.62rem;"
        f"color:#00bcd4;letter-spacing:2px;margin-bottom:6px;text-transform:uppercase;'>{label}</div>"
        f"<div style='font-family:Orbitron,monospace;font-size:1.15rem;"
        f"font-weight:700;color:#ffffff;'>{value}</div>"
        f"<div style='font-family:\"Share Tech Mono\",monospace;font-size:0.7rem;"
        f"color:{sub_color};margin-top:5px;'>{sub}</div>"
        f"</div>"
    )


def sec_title(text):
    st.markdown(
        f"<div style='font-family:\"Share Tech Mono\",monospace;font-size:0.72rem;"
        f"color:#00e5ff;letter-spacing:3px;text-transform:uppercase;"
        f"border-left:3px solid #00f5ff;padding-left:10px;margin:20px 0 10px;'>{text}</div>",
        unsafe_allow_html=True,
    )


# ─────────────────────────────────────────────
#  CSS
# ─────────────────────────────────────────────
st.markdown("""
<style>
@import url('https://fonts.googleapis.com/css2?family=Orbitron:wght@400;700;900&family=Rajdhani:wght@400;500;600;700&family=Share+Tech+Mono&display=swap');
html,body,[data-testid="stApp"]{background:#020b14!important;color:#e8f4f8!important;font-family:'Rajdhani',sans-serif!important;font-size:15px!important;}
[data-testid="stSidebar"]{background:#030d1a!important;border-right:1px solid rgba(0,245,255,0.15)!important;}
[data-testid="stSidebar"] *{color:#e8f4f8!important;}
[data-testid="stSidebar"] label{font-size:0.82rem!important;color:#b0d4e8!important;}
p,li,span{color:#e8f4f8;}
.stMarkdown p{color:#e8f4f8!important;font-size:0.95rem;line-height:1.7;}
.stTabs [data-baseweb="tab"]{font-family:'Share Tech Mono',monospace!important;font-size:0.72rem!important;letter-spacing:1.5px!important;color:#7aacbf!important;}
.stTabs [aria-selected="true"]{color:#00f5ff!important;border-bottom-color:#00f5ff!important;}
.stTabs [data-baseweb="tab-list"]{background:rgba(4,15,28,0.7)!important;border-bottom:1px solid rgba(0,245,255,0.15)!important;}
.stButton>button{background:rgba(0,245,255,0.08)!important;border:1px solid rgba(0,245,255,0.4)!important;color:#00f5ff!important;font-family:'Orbitron',monospace!important;font-size:0.68rem!important;letter-spacing:1.5px!important;border-radius:4px!important;}
.stButton>button:hover{background:rgba(0,245,255,0.18)!important;box-shadow:0 0 14px rgba(0,245,255,0.25)!important;}
.stSelectbox>div>div,.stMultiSelect>div>div{background:rgba(4,15,28,0.92)!important;border:1px solid rgba(0,245,255,0.22)!important;color:#e8f4f8!important;border-radius:4px!important;}
.stTextInput>div>div>input{background:rgba(4,15,28,0.92)!important;border:1px solid rgba(0,245,255,0.22)!important;color:#e8f4f8!important;border-radius:4px!important;font-family:'Share Tech Mono',monospace!important;}
input[type="date"]{background:rgba(4,15,28,0.92)!important;border:1px solid rgba(0,245,255,0.22)!important;color:#e8f4f8!important;border-radius:4px!important;padding:6px 8px;}
div[data-baseweb="slider"] div{background:#00f5ff!important;}
details{border:1px solid rgba(0,245,255,0.15)!important;border-radius:6px!important;background:rgba(4,15,28,0.6)!important;}
summary{color:#00e5ff!important;font-family:'Share Tech Mono',monospace!important;font-size:0.75rem!important;}
[data-testid="stDataFrame"]{border:1px solid rgba(0,245,255,0.15)!important;border-radius:6px!important;}
.stDataFrame thead tr th{background:rgba(0,245,255,0.08)!important;color:#00e5ff!important;font-family:'Share Tech Mono',monospace!important;font-size:0.72rem!important;}
.stDataFrame tbody tr td{color:#e8f4f8!important;font-family:'Share Tech Mono',monospace!important;font-size:0.72rem!important;}
.stAlert{background:rgba(4,15,28,0.92)!important;border:1px solid rgba(0,245,255,0.2)!important;color:#e8f4f8!important;}
label[data-baseweb="checkbox"] span{color:#b0d4e8!important;font-size:0.85rem!important;}
::-webkit-scrollbar{width:5px;height:5px;}
::-webkit-scrollbar-track{background:#020b14;}
::-webkit-scrollbar-thumb{background:rgba(0,245,255,0.2);border-radius:3px;}
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────
#  SIDEBAR
# ─────────────────────────────────────────────
with st.sidebar:
    lang_opt = st.radio("🌐 Language / மொழி", ["en", "ta"],
                        format_func=lambda x: "English" if x == "en" else "தமிழ்",
                        horizontal=True)
    t = T[lang_opt]

    st.markdown(
        f"<div style='font-family:Orbitron,monospace;font-size:1.3rem;font-weight:900;"
        f"color:#00f5ff;text-shadow:0 0 18px rgba(0,245,255,0.5);letter-spacing:4px;"
        f"text-align:center;padding:10px 0 2px;'>VENKAT.AI</div>"
        f"<div style='font-family:\"Share Tech Mono\",monospace;font-size:0.58rem;"
        f"color:#00bcd4;text-align:center;letter-spacing:3px;margin-bottom:12px;'>"
        f"{t['subtitle']}</div>",
        unsafe_allow_html=True,
    )
    st.markdown("---")

    st.markdown(f"**{t['sel_stocks']}**")
    selected = st.multiselect(
        t["sel_stocks"],
        list(DEFAULT_STOCKS.keys()),
        default=["TATAGOLD.NS", "TATSILV.NS"],
        format_func=lambda x: f"{x}  —  {DEFAULT_STOCKS[x]}",
        label_visibility="collapsed",
    )

    st.markdown(f"**{t['cust_tick']}**")
    custom_raw = st.text_input(t["cust_tick"], placeholder=t["cust_ph"],
                                label_visibility="collapsed")
    if custom_raw:
        for raw in [x.strip().upper() for x in custom_raw.split(",") if x.strip()]:
            if raw not in selected:
                with st.spinner(f"Checking {raw}..."):
                    df_test = fetch(raw, period="5d")
                if df_test is not None and len(df_test) > 0:
                    if raw not in DEFAULT_STOCKS:
                        DEFAULT_STOCKS[raw] = raw
                    selected = selected + [raw]
                    st.success(f"✅ {raw} added!")
                else:
                    st.error(f"❌ {raw} not found on Yahoo Finance")

    st.markdown("---")
    st.markdown(f"**{t['period']}**")
    period_map = {
        t["period_1d"]:  "1d",
        t["period_5d"]:  "5d",
        t["period_1mo"]: "1mo",
        t["period_3mo"]: "3mo",
        t["period_6mo"]: "6mo",
        t["period_1y"]:  "1y",
        t["period_2y"]:  "2y",
    }
    plabel   = st.selectbox(t["period"], list(period_map.keys()),
                             index=5, label_visibility="collapsed")
    period   = period_map[plabel]
    intraday = period in ("1d", "5d")

    st.markdown(f"**{t['comp_range']}**")
    ca, cb = st.columns(2)
    with ca:
        comp_start = st.date_input(t["from_d"],
                                    value=date.today() - timedelta(days=180))
    with cb:
        comp_end = st.date_input(t["to_d"], value=date.today())

    st.markdown("---")
    st.markdown(f"**{t['pred_days']}**")
    pred_days = st.slider(t["pred_days"], 7, 60, 30, label_visibility="collapsed")

    st.markdown(f"**{t['indicators']}**")
    show_ma  = st.checkbox(t["show_ma"],  value=True)
    show_bb  = st.checkbox(t["show_bb"],  value=True)
    show_vol = st.checkbox(t["show_vol"], value=True)

    st.markdown("---")
    if st.button(t["refresh"], use_container_width=True):
        st.cache_data.clear()

    st.markdown(
        f"<div style='font-family:\"Share Tech Mono\",monospace;font-size:0.6rem;"
        f"color:#445566;line-height:1.9;margin-top:8px;'>"
        f"{t['data_src']}<br>{t['models_lbl']}<br>"
        f"<span style='color:#00bcd4;opacity:0.6;'>VENKAT.AI v4.0</span></div>",
        unsafe_allow_html=True,
    )

# ─────────────────────────────────────────────
#  HEADER
# ─────────────────────────────────────────────
st.markdown(
    f"<div style='text-align:center;padding:14px 0 4px;'>"
    f"<span style='font-family:Orbitron,monospace;font-size:2.5rem;font-weight:900;"
    f"background:linear-gradient(90deg,#00f5ff 0%,#a855f7 50%,#00ff88 100%);"
    f"-webkit-background-clip:text;-webkit-text-fill-color:transparent;"
    f"background-clip:text;letter-spacing:8px;display:inline-block;'>VENKAT.AI</span>"
    f"<div style='font-family:\"Share Tech Mono\",monospace;font-size:0.7rem;"
    f"color:#00bcd4;letter-spacing:4px;margin-top:4px;'>{t['tagline']}</div>"
    f"</div>",
    unsafe_allow_html=True,
)

if not selected:
    st.warning("👈 Select at least one stock from the sidebar to begin.")
    st.stop()

# ─────────────────────────────────────────────
#  SNAPSHOT
# ─────────────────────────────────────────────
sec_title(f"📊 {t['snapshot']}")
snap_cols = st.columns(min(len(selected), 6))
for i, tk in enumerate(selected[:6]):
    df_s = fetch(tk, period="5d")
    with snap_cols[i]:
        if df_s is not None and len(df_s) >= 2:
            lp   = float(df_s["Close"].squeeze().iloc[-1])
            pp   = float(df_s["Close"].squeeze().iloc[-2])
            chg  = lp - pp
            pct  = chg / pp * 100
            cur  = "₹" if ".NS" in tk else "$"
            sc   = "#00ff88" if chg >= 0 else "#ff3366"
            arr  = "▲" if chg >= 0 else "▼"
            name = DEFAULT_STOCKS.get(tk, tk)
            st.markdown(mcard(name, f"{cur}{lp:,.2f}",
                               f"{arr} {chg:+.2f} ({pct:+.2f}%)", sub_color=sc),
                         unsafe_allow_html=True)
        else:
            st.markdown(mcard(tk, "N/A"), unsafe_allow_html=True)

# ─────────────────────────────────────────────
#  TABS
# ─────────────────────────────────────────────
sec_title(f"📈 {t['analysis']}")
tab_labels = [DEFAULT_STOCKS.get(tk, tk).split()[0] for tk in selected]
tabs = st.tabs(tab_labels)

for tab, ticker in zip(tabs, selected):
    with tab:
        cur = "₹" if ".NS" in ticker else "$"

        with st.spinner(f"Loading {ticker}..."):
            df = fetch(ticker, period=period)

        if df is None or len(df) < 5:
            st.error(t["no_data"])
            continue

        df = indicators(df)

        # Always fetch 2Y data for predictions regardless of chart period
        preds = {}
        if not intraday:
            with st.spinner("Running ML predictions..."):
                preds = run_preds(ticker, pred_days)

        c    = df["Close"].squeeze()
        last = float(c.iloc[-1])
        prev = float(c.iloc[-2]) if len(c) > 1 else last
        chg  = last - prev; pct = chg / prev * 100

        hi52   = float(df["High"].squeeze().tail(252).max())
        rsi_v  = float(df["RSI"].iloc[-1])  if "RSI"  in df.columns and df["RSI"].notna().any()  else 50.0
        macd_v = float(df["MACD"].iloc[-1]) if "MACD" in df.columns and df["MACD"].notna().any() else 0.0
        atr_v  = float(df["ATR"].iloc[-1])  if "ATR"  in df.columns and df["ATR"].notna().any()  else 0.0

        sig, conf, sig_details = compute_signal(df)
        sig_color = {"BUY": "#00ff88", "SELL": "#ff3366", "HOLD": "#ffaa00"}[sig]
        sig_bg    = {"BUY": "rgba(0,255,136,0.09)", "SELL": "rgba(255,51,102,0.09)",
                     "HOLD": "rgba(255,170,0,0.09)"}[sig]

        n_open, n_close = next_day_pred(df, preds)

        # ── Metric cards
        cols = st.columns(7)
        metric_items = [
            (t["last_price"],  f"{cur}{last:,.2f}",
             f"{'▲' if chg>=0 else '▼'} {chg:+.2f} ({pct:+.2f}%)",
             "#00ff88" if chg >= 0 else "#ff3366"),
            (t["rsi"], f"{rsi_v:.1f}",
             t["overbought"] if rsi_v > 70 else t["oversold"] if rsi_v < 30 else t["neutral"],
             "#ff3366" if rsi_v > 70 else "#00ff88" if rsi_v < 30 else "#ffaa00"),
            (t["macd"], f"{macd_v:+.2f}",
             t["bullish"] if macd_v >= 0 else t["bearish"],
             "#00ff88" if macd_v >= 0 else "#ff3366"),
            (t["high52"], f"{cur}{hi52:,.2f}",
             f"{(last-hi52)/hi52*100:.1f}% from high", "#8baabb"),
            (t["atr"], f"{cur}{atr_v:.2f}", "Volatility range", "#8baabb"),
            (t["next_open"],
             f"{cur}{n_open:,.2f}" if n_open else "—",
             "Predicted tomorrow open", "#00bcd4"),
            (t["next_close"],
             f"{cur}{n_close:,.2f}" if n_close else "—",
             "Predicted tomorrow close", "#bf7fff"),
        ]
        for col, (label, val, sub, sc) in zip(cols, metric_items):
            with col:
                st.markdown(mcard(label, val, sub, sub_color=sc), unsafe_allow_html=True)

        # ── Signal banner
        at = action_text(sig, last, conf, cur)
        st.markdown(
            f"<div style='background:{sig_bg};border:1px solid {sig_color};"
            f"border-radius:8px;padding:12px 18px;margin:14px 0;"
            f"display:flex;align-items:center;gap:16px;flex-wrap:wrap;'>"
            f"<span style='font-family:Orbitron,monospace;font-size:1.1rem;"
            f"font-weight:900;color:{sig_color};letter-spacing:4px;"
            f"text-shadow:0 0 12px {sig_color};min-width:60px;'>{sig}</span>"
            f"<span style='font-family:\"Share Tech Mono\",monospace;font-size:0.76rem;"
            f"color:#e8f4f8;flex:1;'>{at}</span>"
            f"</div>",
            unsafe_allow_html=True,
        )

        if intraday:
            st.info(t["intraday_note"])

        # ── One-line smart summary
        trend_5d  = float(c.iloc[-1]) - float(c.iloc[-5]) if len(c) >= 5 else 0
        trend_dir = "📈 rising" if trend_5d > 0 else "📉 falling"
        rsi_note  = "overbought" if rsi_v > 70 else "oversold — potential bounce" if rsi_v < 30 else "neutral"
        macd_note = "bullish" if macd_v > 0 else "bearish"
        ml_note   = ""
        if preds:
            all30 = [float(v[min(29,len(v)-1)]) for v in preds.values() if v is not None and len(v)>0]
            if all30:
                avg30 = float(np.mean(all30))
                ml_pct = (avg30 - last) / last * 100
                ml_note = f" · ML models forecast **{ml_pct:+.1f}%** over 30 days ({cur}{avg30:,.2f})"
        verdict_map = {
            "BUY":  f"✅ **Verdict: Consider BUYING** — price is {trend_dir}, RSI is {rsi_note}, MACD is {macd_note}{ml_note}.",
            "SELL": f"🚫 **Verdict: Consider SELLING / Avoid buying** — price is {trend_dir}, RSI is {rsi_note}, MACD is {macd_note}{ml_note}.",
            "HOLD": f"⏸ **Verdict: HOLD / Wait** — price is {trend_dir}, RSI is {rsi_note}, MACD is {macd_note}{ml_note}.",
        }
        summary_color = {"BUY": "rgba(0,255,136,0.07)", "SELL": "rgba(255,51,102,0.07)", "HOLD": "rgba(255,170,0,0.07)"}[sig]
        summary_border = {"BUY": "rgba(0,255,136,0.35)", "SELL": "rgba(255,51,102,0.35)", "HOLD": "rgba(255,170,0,0.35)"}[sig]
        st.markdown(
            f"<div style='background:{summary_color};border:1px solid {summary_border};"
            f"border-radius:6px;padding:10px 16px;margin-bottom:12px;"
            f"font-family:Rajdhani,sans-serif;font-size:0.97rem;color:#e8f4f8;line-height:1.5;'>"
            f"{verdict_map[sig]}</div>",
            unsafe_allow_html=True,
        )

        # ── Main chart
        fig = main_chart(df, ticker, preds, show_ma, show_bb, show_vol,
                          pred_days, intraday)
        st.plotly_chart(fig, use_container_width=True,
                        config={"displayModeBar": True, "scrollZoom": True})

        # ── Chart legend
        with st.expander(f"📖 {t['legend']}", expanded=False):
            leg_items = [
                (C["up"],     "█", "Green candle — Price rose (Close > Open)"),
                (C["dn"],     "█", "Red candle — Price fell (Close < Open)"),
                (C["ma20"],   "─", "MA 20  — 20-day moving avg (short-term trend)"),
                (C["ma50"],   "─", "MA 50  — 50-day moving avg (medium trend)"),
                (C["ma200"],  "─", "MA 200 — 200-day moving avg (long-term trend)"),
                ("rgba(255,170,0,0.8)", "╌", "Bollinger Bands — Price volatility channel"),
                (C["p_lstm"], "─", "▶ LSTM prediction — solid green line"),
                (C["p_rf"],   "╌", "▶ Random Forest — dashed purple line"),
                (C["p_lr"],   "╌", "▶ Linear Trend — dash-dot cyan line"),
                (C["p_xgb"],  "···", "▶ XGBoost — dotted amber line"),
                ("#00e5ff",   "~", "RSI — Momentum (>70 sell zone, <30 buy zone)"),
                (C["amber"],  "─", "Vol MA20 — Average trading volume"),
                ("#00f5ff",   "┊", "NOW line — separates history from forecast"),
                ("#ffffff",   "◆", "Diamond marker — next-day predicted price"),
            ]
            leg_cols = st.columns(2)
            for i, (color, sym, desc) in enumerate(leg_items):
                with leg_cols[i % 2]:
                    st.markdown(
                        f"<div style='display:flex;align-items:center;gap:8px;"
                        f"margin-bottom:7px;padding:4px 6px;"
                        f"background:rgba(0,229,255,0.04);border-radius:4px;'>"
                        f"<span style='color:{color};font-size:1.1rem;min-width:18px;"
                        f"text-align:center;'>{sym}</span>"
                        f"<span style='font-family:\"Share Tech Mono\",monospace;"
                        f"font-size:0.7rem;color:#c8e4f0;line-height:1.4;'>{desc}</span>"
                        f"</div>",
                        unsafe_allow_html=True,
                    )

        # ── Prediction table
        col_p, col_m = st.columns([1.3, 1])
        with col_p:
            sec_title(f"🔮 {t['predictions']}")
            if preds:
                rows = []
                for model, vals in preds.items():
                    if vals is None or len(vals) == 0:
                        continue
                    p7  = float(vals[min(6,  len(vals)-1)])
                    p14 = float(vals[min(13, len(vals)-1)])
                    p30 = float(vals[min(29, len(vals)-1)])
                    rows.append({
                        t["model_col"]: model,
                        t["7d_col"]:    f"{cur}{p7:,.2f}",
                        t["14d_col"]:   f"{cur}{p14:,.2f}",
                        t["30d_col"]:   f"{cur}{p30:,.2f}",
                        t["chg7_col"]:  f"{(p7-last)/last*100:+.2f}%",
                        t["chg30_col"]: f"{(p30-last)/last*100:+.2f}%",
                        t["dir_col"]:   "▲" if p30 > last else "▼",
                    })
                if rows:
                    st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
                    all30 = [float(v[min(29, len(v)-1)]) for v in preds.values()
                              if v is not None and len(v) > 0]
                    if all30:
                        avg30  = float(np.mean(all30))
                        chg30  = (avg30 - last) / last * 100
                        agree  = sum(1 for x in all30 if x >= last) / len(all30) * 100
                        ec1, ec2 = st.columns(2)
                        with ec1:
                            st.markdown(mcard(t["ensemble"], f"{cur}{avg30:,.2f}",
                                               f"{'▲' if avg30>=last else '▼'} {chg30:+.1f}%",
                                               "#00ff88" if avg30>=last else "#ff3366"),
                                         unsafe_allow_html=True)
                        with ec2:
                            ac = "#00ff88" if agree >= 50 else "#ff3366"
                            st.markdown(mcard(t["agreement"], f"{agree:.0f}%",
                                               t["bullish"] if agree>=50 else t["bearish"],
                                               ac),
                                         unsafe_allow_html=True)
            else:
                if intraday:
                    st.info(t["intraday_note"])
                else:
                    st.warning("⚠ Could not generate predictions — ticker may have insufficient history on Yahoo Finance.")

        with col_m:
            sec_title("📉 MACD")
            if "MACD" in df.columns and df["MACD"].notna().any():
                st.plotly_chart(macd_chart(df), use_container_width=True,
                                config={"displayModeBar": False})
            else:
                st.info("Insufficient data for MACD.")

        # ── Signal breakdown
        with st.expander(f"🔍 {t['sig_break']}", expanded=False):
            if sig_details:
                for pattern, direction, confidence, reason in sig_details:
                    sc = {"BUY": "#00ff88", "SELL": "#ff3366", "HOLD": "#ffaa00"}[direction]
                    bg = {"BUY": "rgba(0,255,136,0.07)",
                          "SELL": "rgba(255,51,102,0.07)",
                          "HOLD": "rgba(255,170,0,0.07)"}[direction]
                    st.markdown(
                        f"<div style='display:flex;align-items:center;gap:12px;"
                        f"padding:9px 12px;margin-bottom:5px;background:{bg};"
                        f"border-left:3px solid {sc};border-radius:4px;'>"
                        f"<span style='font-family:\"Share Tech Mono\",monospace;"
                        f"font-size:0.78rem;color:#c8e4f0;flex:1.2;'>{pattern}</span>"
                        f"<span style='font-family:Orbitron,monospace;font-size:0.68rem;"
                        f"font-weight:700;color:{sc};padding:2px 10px;"
                        f"border:1px solid {sc};border-radius:3px;white-space:nowrap;'>{direction}</span>"
                        f"<span style='font-family:\"Share Tech Mono\",monospace;"
                        f"font-size:0.72rem;color:#e8f4f8;min-width:44px;text-align:right;'>"
                        f"{confidence*100:.0f}%</span>"
                        f"<span style='font-family:\"Share Tech Mono\",monospace;"
                        f"font-size:0.68rem;color:#7aacbf;flex:2;text-align:right;'>{reason}</span>"
                        f"</div>",
                        unsafe_allow_html=True,
                    )
            else:
                st.info(t["no_signal"])

        st.markdown("---")

# ─────────────────────────────────────────────
#  COMPARISON  (date range based)
# ─────────────────────────────────────────────
if len(selected) > 1:
    sec_title(f"📊 {t['comparison']}")
    st.markdown(
        f"<div style='font-family:\"Share Tech Mono\",monospace;font-size:0.72rem;"
        f"color:#7aacbf;margin-bottom:8px;'>"
        f"From {comp_start} to {comp_end} — normalised % return from start date</div>",
        unsafe_allow_html=True,
    )
    comp_fig = comparison_chart(selected, comp_start, comp_end, lang_opt)
    st.plotly_chart(comp_fig, use_container_width=True,
                    config={"displayModeBar": True})

# ─────────────────────────────────────────────
#  DISCLAIMER
# ─────────────────────────────────────────────
st.markdown("---")
st.markdown(
    f"<div style='background:rgba(255,51,102,0.06);border:1px solid rgba(255,51,102,0.3);"
    f"border-radius:8px;padding:18px 22px;margin:16px 0 8px;'>"
    f"<div style='font-family:Orbitron,monospace;font-size:0.8rem;font-weight:700;"
    f"color:#ff3366;letter-spacing:2px;margin-bottom:10px;'>{t['disclaimer_title']}</div>"
    f"<div style='font-family:\"Rajdhani\",sans-serif;font-size:0.92rem;"
    f"color:#d8eaf4;line-height:1.75;'>{t['disclaimer']}</div>"
    f"</div>",
    unsafe_allow_html=True,
)
st.markdown(
    f"<div style='text-align:center;font-family:\"Share Tech Mono\",monospace;"
    f"font-size:0.62rem;color:#334455;padding:10px;'>"
    f"VENKAT.AI Trading Intelligence v4.0 &nbsp;·&nbsp; "
    f"{t['data_src']} &nbsp;·&nbsp; {t['models_lbl']}"
    f"</div>",
    unsafe_allow_html=True,
)